#------------------------------------------------
# references powerpoint
#------------------------------------------------
# title: 5 animations de texte faciles sur POWERPOINT
# link: https://www.youtube.com/watch?v=ZHLhK2_xjFE
# topic: anime un texte
#------------------------------------------------
# animation {1}
# animation {fouet}
#------------------------------------------------
...
# ajoute une animation {fouet}
...
-> selectionner le texte
...
-> menu -> animations -> animation avancee
-> ajouter une animation -> autres effets d entree
-> captivant -> fouet -> ok
...
# ouvre le volet animation
...
-> menu -> animations -> animation avancee -> volet animation
...
# regle le minuatge
...
-> ouvrir le volet animation
-> selectionner le texte
...
-> volet animation
-> {animation} -> clic-droit -> demarrer avec le precedent
-> {animation} -> clic-droit -> minuatage
...
-> minuatge
-> debut -> avec la precedente
-> delai -> {0} secondes
-> duree -> {0.5} secondes
...
-> effet -> ameliorations
-> son -> aucun son
-> apres l animation -> ne pas estomper
-> animer le texte -> par lettre
-> animer le texte -> {50} % delai entre les lettres
...
-> ok
...
# demarre le daiporama
...
-> menu -> diaporama -> a partir du debut
...
# supprime une animation
...
-> ouvrir le volet animation
-> selectionner le texte
...
-> volet animation
-> {aniamtion} -> clic-droit -> supprimer
...
# duplique une diapositive
...
-> {diapositive} -> clic-droit -> dupliquer la diapositive
...
#------------------------------------------------
# animation {2}
# animation {entree brusque}
#------------------------------------------------
...
# ajoute une animation {entree brusque}
...
-> selectionner le texte
...
-> menu -> animations -> animation -> {fleche-bas}
-> entree -> entree brusque
...
# ajoute l'option {a partir de la droite}
...
-> selectionner le texte
-> selectionner l animation
...
-> menu -> animations -> animation
-> options de l effet -> a partir de la droite
...
# regle le munitage
...
-> selctionner le texte
-> ouvrir le volet animation
...
-> volet animation
-> {animation} -> clic-droit -> demarrer avec le precedent
-> {animation} -> clic-droit -> minutage
...
-> minuatge
-> debut -> avec la precedente
-> delai -> {0.2} secondes
-> duree -> {1.2} secondes
...
-> effet -> parametres
-> sens -> a partir du coin inferieur
-> demarrage en douceur -> {0.25} secondes
-> fin en douceur -> {0} secondes
-> rebondir fin -> {0.90} secondes
->
...
-> effet -> ameliorations
-> son -> aucun son
-> apres l animation -> ne pas estomper
-> animer le texte -> par lettre
-> animer le texte -> {5} % delai entre lettres
...
-> ok
...
# teste une animation
...
-> menu -> animations -> animation -> apercu
#------------------------------------------------
# animation {3}
# animation {zoom simple}
#------------------------------------------------
...
# ajoute une animation {zoom simple}
...
-> selectionner un texte
...
-> menu -> animations -> animation avancee
-> ajouter une animation -> autres effets d entree
-> modere -> {zoom simple} -> ok
...
# ajoute l'option {vers l'arriere}
...
-> selectionner le texte
-> selectionner l animation
...
-> menu -> animations -> animation
-> options de l effet -> {vers l arriere}
...
# regle le munitage
...
-> selctionner le texte
-> ouvrir le volet animation
...
-> volet animation
-> {animation} -> clic-droit -> demarrer avec le precedent
-> {animation} -> clic-droit -> minutage
...
-> minuatge
-> debut -> avec la precedente
-> delai -> {0} secondes
-> duree -> {0.2} secondes
...
-> effet -> parametres
-> zoom -> {vers l arriere}
->
...
-> effet -> ameliorations
-> son -> aucun son
-> apres l animation -> ne pas estomper
-> animer le texte -> par lettre
-> animer le texte -> {10} % delai entre lettres
...
-> ok
...
#------------------------------------------------
# animation {4}
# animation {vague}
#------------------------------------------------
...
# ajoute une animation {vague}
...
-> selectionner un texte
...
-> menu -> animations -> animation avancee
-> ajouter une animation -> accentuation -> vague
...
# regle le munitage
...
-> selctionner le texte
-> ouvrir le volet animation
...
-> volet animation
-> {animation} -> clic-droit -> demarrer avec le precedent
-> {animation} -> clic-droit -> minutage
...
-> minuatge
-> debut -> avec la precedente
-> delai -> {0} secondes
-> duree -> {0.5} secondes
...
-> effet -> ameliorations
-> son -> aucun son
-> apres l animation -> ne pas estomper
-> animer le texte -> par lettre
-> animer le texte -> {30} % delai entre lettres
...
-> ok
...
#------------------------------------------------
#
#------------------------------------------------
...
# ajoute une animation {zoom simple}
...
-> selectionner un texte
...
-> menu -> animations -> animation avancee
-> ajouter une animation -> autres effets d entree
-> modere -> {zoom simple} -> ok
...
# ajoute l'option {vers l'avant}
...
-> selectionner le texte
-> selectionner l animation
...
-> menu -> animations -> animation
-> options de l effet -> {vers l avant}
...
# ajoute une animation {zoom simple}
...
-> selectionner un texte
...
-> menu -> animations -> animation avancee
-> ajouter une animation -> accentuation -> agrandir-retrecir
...
# ajoute l'option {vers l'avant}
...
-> selectionner le texte
-> selectionner l animation
...
-> menu -> animations -> animation
-> options de l effet -> sens -> {les deux}
...
# regle le munitage
...
-> selctionner le texte
-> ouvrir le volet animation
...
-> volet animation
-> {animation-1} -> clic-droit -> demarrer avec le precedent
-> {animation-2} -> clic-droit -> demarrer avec le precedent
...
-> {animation-2} -> clic-droit -> minutage
...
-> minuatge
-> debut -> avec la precedente
-> delai -> {0.2} secondes
-> duree -> {2} secondes
...
-> effet -> parametres
-> taille -> personnalise -> {100} %
-> demarrage en douceur -> {0} secondes
-> fin en douceur -> {0} secondes
-> rebondir fin -> {2} secondes
...
-> effet -> ameliorations
-> son -> aucun son
-> apres l animation -> ne pas estomper
-> animer le texte -> tout simultanement
...
-> ok
...
#------------------------------------------------
