#------------------------------------------------
# references powerpoint
#------------------------------------------------
# title: How to Add Audio & Captions to PowerPoint Slides - Make Your Presentations Accessible with Subtitles
# link: https://www.youtube.com/watch?v=kcQvsBlGCQA&t=11s
# topic: ajoute des sous-titres a une diapositive
#------------------------------------------------
...
# telecharge stamp
...
-> https://sourceforge.net/projects/stamp-addin/
-> files
-> download lastest version
...
# installe stamp
...
-> STAMP 1.6.0 Setup.msi
-> next
-> i accept the terms in the license agreement
-> next
-> "C:\Program Files (x86)\Microsoft\Subtitling Add-In for Microsoft PowerPoint"
-> next
-> install
-> next
-> oui
-> finish
...
-> redemarrer powerpoint
...
# ajoute une note
...
-> menu -> affichage -> afficher -> notes
...
-> cliquez pour ajouter une note
...
-> Bonjour tout le monde
...
# enregistre un fichier audio
...
-> menu -> insertion -> media
-> audio -> enregsitrer l audio
...
-> enregistrer un son
-> nom -> {nom-audio}
-> cliquer sur le bouton {enregistrer-audio} en forme {rond-rouge}
-> cliquer sur le bouton {arreter-enregistrement} en forme {carre-gris}
-> cliquer sur le bouton {lire-audio} en forme {triangle-gris}
...
# ajoute un sous-titre a un fichier audio
...
-> copier le texte du {sous-titre}
-> selectionner le fichier audio
...
-> menu -> lecture -> captions -> add cpations -> create captions
-> add a new caption
...
-> start time -> 00:00:00.0
-> sendt time -> 00:00:06.0
-> caption text -> coller le texte du {sous-titre}
-> create
...
# centre un sous-titre
...
-> selectionner le fichier audio
...
-> menu -> lecture -> captions -> edit cpations
...
-> caption text -> selectionner le texte du {sous-titre}
-> alignement -> {align center}
-> update
...
# modifie la police d'un sous-titre
...
-> selectionner le fichier audio
...
-> menu -> lecture -> captions -> edit cpations
...
-> caption text -> selectionner le texte du {sous-titre}
-> police -> {arial narrow}
-> update
...
#------------------------------------------------
